CREATE TABLE "users" (
                         "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                         "login" varchar(32) UNIQUE NOT NULL,
                         "password_hash" varchar(255) NOT NULL
);

CREATE TABLE "orders" (
                          "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                          "user_id" integer NOT NULL,
                          "number" text UNIQUE NOT NULL,
                          "status" varchar(255) NOT NULL CHECK (status IN ('NEW', 'PROCESSING', 'INVALID', 'PROCESSED')),
                          "accrual" decimal(10,2),
                          "uploaded_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "withdrawals" (
                               "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                               "user_id" integer NOT NULL,
                               "order" text NOT NULL,
                               "sum" decimal(10,2) NOT NULL,
                               "processed_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "withdrawals" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

CREATE INDEX idx_orders_user_id ON orders(user_id);
CREATE INDEX idx_withdrawals_user_id ON withdrawals(user_id);
